### ISSUE TITLE
addin readme

### ISSUE THREAD

**Issue by pacav69** [nickgammon/MAX7219_Dot_Matrix#3]
Hi Nick,

Great work you have done mate keep it up.

I suggest adding in the link to the bitBangedSPI, which is a requirement for the example sketches to compile, into the readme.md file.

https://github.com/nickgammon/bitBangedSPI

p.s. this also works with a multi matrix such as a 4 in 1 display.

**Comment by nickgammon** [comment]
Done, thanks for the suggestion.
