### ISSUE TITLE
adding arduino library properties

### ISSUE THREAD

**Issue by pacav69** [nickgammon/MAX7219_Dot_Matrix#4]
This is just a suggestion, have you considered using the arduino library properties so that it is easier to install your great libraries. 
Here is the link to the spec. 
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

**Comment by nickgammon** [comment]
That looks interesting. I'll look into that in a few weeks. I won't be able to do anything in the immediate future, but thanks for the suggestion.

**Comment by pacav69** [comment]
i've added the library.properties and keywords.txt to a branch and submitted a pull request for you to review.

**Comment by nickgammon** [comment]
I'm going on holiday for a few weeks. I'll review it when I get back. Thanks for setting it up. :)

**Comment by nickgammon** [comment]
Commit merged, thanks!
