### ISSUE TITLE
Multiple chips look reversed

### ISSUE THREAD

**Issue by masoudr** [nickgammon/MAX7219_Dot_Matrix#7]
Hi,
I'm using this library for a 4 chip Dot Matrix and it is working fine for current hardware.
I've bought a new 4 Dot Matrix which seems the same (at least on MAX7219). But my problem is the display looks reverse. For example on a normal display if I had this:
`A B C D`
But in new hardware it looks like this:
`D C B A`

Thanks.

**Comment by nickgammon** [comment]
It isn't clear from your comment exactly what hardware you have.

The simplest thing would be to change the code to output the characters in reverse order.

In C you can do that with strrev where **s** is the string to be reversed (a null-terminated string):

```c
strrev(s);
```

**Comment by masoudr** [comment]
Thanks for the answer. I'm using the Cascaded MAX7219 Dot Matrix Module. The old module I have is working fine but the new one which seems identical (both has MAX7219) looks reversed.

**Comment by masoudr** [comment]
I tried your method and it worked but I found another way to change `sendString` to work with new hardware:
```
void MAX7219_Dot_Matrix::sendString (const char * s)
{
  byte chip;

  for (chip = 0; chip < chips_ && *s; chip++)
    sendChar (chips_ -1 -chip, *s++);

 // space out rest
  while (chip < (chips_))
    {
      sendChar (chips_ - 1 - chip, ' ');
      chip++;
    }

}  // end of sendString
```
Now I need to modify `sendSmooth` function and my problem is it is reversed orientation and the direction is opposite so I don't know how to fix it. Can you give me more hint on how to fix this function?

I also tried to use [this](https://github.com/MajicDesigns/MD_MAX72XX) and the option `HARDWARE_TYPE MD_MAX72XX::ICSTATION_HW` worked for current hardware. Is there any option in your library that I need to change for current hardware or I need to reimplement functions as I did?

**Comment by nickgammon** [comment]
Is everything reversed or just the ones on the side? Probably reverse:

```c++
    // get pixels to left of current character in case "pixel" is negative
 ...
    // get the current character
...
    // get pixels to right of current character in case "pixel" is positive
```

So start with the character on the right, then the current one, then the character on the left.

Simpler is probably to use strrev as I suggested before.

>  Is there any option in your library that I need to change for current hardware or I need to reimplement functions as I did?

There are no other options along those lines.
